// COMPOSITION ROOT.
//
// Riverpod is the ONLY composition mechanism in this application. There is no
// service locator, no `GetIt`, no static singleton, and no global mutable
// instance. Everything is constructed here and reached through `ref`.
//
// Riverpod types must not appear in a feature's DOMAIN layer. The permitted
// shape is:
//
//     // features/<feature>/domain/…  — pure Dart, no Riverpod
//     abstract interface class ThingRepository {
//       Future<Result<Thing>> load();
//     }
//     final class LoadThing {                 // use case
//       const LoadThing(this._repository);
//       final ThingRepository _repository;
//       Future<Result<Thing>> call() => _repository.load();
//     }
//
//     // features/<feature>/presentation/…  — providers live HERE, not in domain
//     final loadThingProvider = Provider<LoadThing>(
//       (Ref ref) => LoadThing(ref.watch(thingRepositoryProvider)),
//     );
//
// Three providers are EXTENSION POINTS for feature workstreams. Override them
// in the ProviderScope; do not edit this file to add a feature:
//   * [featureRoutesProvider]        — protected routes;
//   * [startupScreenOverridesProvider] — real screens for gate states;
//   * [homeScreenBuilderProvider]    — the signed-in landing surface.
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart' show ThemeData;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../core/errors/result.dart';
import '../../core/localization/locale_preference.dart';
import '../../core/logging/app_logger.dart';
import '../../core/networking/api_transport.dart';
import '../../core/networking/dio_api_transport.dart';
import '../../core/networking/generated/karar_api_client.dart';
import '../../core/networking/generated/models.dart';
import '../../core/networking/network_status.dart';
import '../../core/networking/retry_policy.dart';
import '../../core/networking/timeouts.dart';
import '../../core/networking/token_refresh_coordinator.dart';
import '../../core/security/app_lock.dart';
import '../../core/security/flutter_secure_store.dart';
import '../../core/security/local_security_state_store.dart';
import '../../core/security/secure_store.dart';
import '../../core/security/session_manager.dart';
import '../../core/security/session_token_codec.dart';
import '../../core/security/session_tokens.dart';
import '../../core/security/token_store.dart';
import '../../core/storage/key_value_store.dart';
import '../../core/utilities/clock.dart';
import '../../core/utilities/correlation_id.dart';
import '../configuration/app_configuration.dart';
import '../configuration/configuration_loader.dart';
import '../lifecycle/api_bootstrap_gateway.dart';
import '../lifecycle/startup_coordinator.dart';
import '../lifecycle/startup_listenable.dart';
import '../lifecycle/startup_state.dart';
import '../routing/app_router.dart';

/// Thrown when a provider that the bootstrap sequence must override is read
/// without an override. Failing here is better than silently constructing a
/// second, unconfigured instance.
final class MissingOverrideError extends Error {
  MissingOverrideError(this.providerName);

  final String providerName;

  @override
  String toString() => 'Provider $providerName must be overridden by the bootstrap sequence.';
}

// ---------------------------------------------------------------------------
// Supplied by the bootstrap sequence
// ---------------------------------------------------------------------------

/// The validated build configuration, or the failure that invalidated it.
///
/// Held as a `Result` rather than a value so the startup coordinator can turn
/// an invalid configuration into a CONFIG_INVALID state instead of a crash.
final Provider<Result<AppConfiguration>> configurationResultProvider =
    Provider<Result<AppConfiguration>>(
  (Ref ref) => throw MissingOverrideError('configurationResultProvider'),
);

/// Non-sensitive preference storage, opened asynchronously at bootstrap.
///
/// Locale, theme, dismissed hints. NOT the application-lock choice and NOT the
/// persisted-session abandonment marker: those are security state and live in
/// [localSecurityStateStoreProvider], which reports a storage failure instead
/// of falling back to memory. See `core/storage/key_value_store.dart`.
final Provider<KeyValueStore> keyValueStoreProvider = Provider<KeyValueStore>(
  (Ref ref) => throw MissingOverrideError('keyValueStoreProvider'),
);

/// Durable local SECURITY state, opened asynchronously at bootstrap.
///
/// Two booleans that decide whether protected content renders. Required rather
/// than defaulted: a default would have to be either an in-memory store, which
/// answers "the lock is off" on a device whose storage failed, or an
/// unavailable one, which would block a shell that simply forgot to wire it.
/// Failing loudly at composition time is better than either.
final Provider<LocalSecurityStateStore> localSecurityStateStoreProvider =
    Provider<LocalSecurityStateStore>(
  (Ref ref) => throw MissingOverrideError('localSecurityStateStoreProvider'),
);

/// Diagnostics sink. Silent by default so a test that forgets to override it
/// cannot start writing.
final Provider<AppLogger> loggerProvider = Provider<AppLogger>((Ref ref) => AppLogger.silent);

// ---------------------------------------------------------------------------
// Extension points for feature workstreams
// ---------------------------------------------------------------------------

/// Protected routes, contributed by feature workstreams.
final Provider<List<RouteBase>> featureRoutesProvider =
    Provider<List<RouteBase>>((Ref ref) => const <RouteBase>[]);

/// Real screens for startup gate states, contributed by feature workstreams.
final Provider<Map<StartupStage, StartupScreenBuilder>> startupScreenOverridesProvider =
    Provider<Map<StartupStage, StartupScreenBuilder>>(
  (Ref ref) => const <StartupStage, StartupScreenBuilder>{},
);

/// The signed-in landing surface.
final Provider<StartupScreenBuilder?> homeScreenBuilderProvider =
    Provider<StartupScreenBuilder?>((Ref ref) => null);

/// The light theme. Null falls back to the framework default; the
/// design-system workstream overrides it.
final Provider<ThemeData?> lightThemeProvider = Provider<ThemeData?>((Ref ref) => null);

/// The dark theme. See [lightThemeProvider].
final Provider<ThemeData?> darkThemeProvider = Provider<ThemeData?>((Ref ref) => null);

// ---------------------------------------------------------------------------
// Foundations
// ---------------------------------------------------------------------------

final Provider<Clock> clockProvider = Provider<Clock>((Ref ref) => const SystemClock());

final Provider<CorrelationIdGenerator> correlationIdGeneratorProvider =
    Provider<CorrelationIdGenerator>((Ref ref) => RandomCorrelationIdGenerator());

final Provider<LocalePreferences> localePreferencesProvider = Provider<LocalePreferences>(
  (Ref ref) => LocalePreferences(ref.watch(keyValueStoreProvider)),
);

final Provider<AppLockGate> appLockGateProvider = Provider<AppLockGate>(
  (Ref ref) => AppLockGate(securityState: ref.watch(localSecurityStateStoreProvider)),
);

// ---------------------------------------------------------------------------
// Security
// ---------------------------------------------------------------------------

final Provider<SecureStore> secureStoreProvider = Provider<SecureStore>(
  (Ref ref) => FlutterSecureStore(logger: ref.watch(loggerProvider)),
);

/// The credential store, with the durable invalidation marker attached.
///
/// The marker is not optional in production: it is the only thing that stops a
/// credential whose erase FAILED from being restored on the next cold launch.
/// It is kept in local security state rather than in the secure store on
/// purpose — a marker written through the very port that just refused a delete
/// would be unavailable at precisely the moment it is needed. See
/// `core/security/token_store.dart` for the semantics and for what the
/// arrangement still does not protect against.
final Provider<TokenStore> tokenStoreProvider = Provider<TokenStore>(
  (Ref ref) => SecureTokenStore(
    ref.watch(secureStoreProvider),
    invalidation:
        PersistedSessionInvalidation(ref.watch(localSecurityStateStoreProvider)),
  ),
);

final Provider<SessionManager> sessionManagerProvider = Provider<SessionManager>((Ref ref) {
  final manager = SessionManager(
    store: ref.watch(tokenStoreProvider),
    logger: ref.watch(loggerProvider),
  );
  ref.onDispose(manager.dispose);
  return manager;
});

final Provider<SessionTokenCodec> sessionTokenCodecProvider =
    Provider<SessionTokenCodec>((Ref ref) => const SessionTokenCodec());

// ---------------------------------------------------------------------------
// Networking
// ---------------------------------------------------------------------------

final Provider<NetworkStatusTracker> networkStatusProvider =
    Provider<NetworkStatusTracker>((Ref ref) {
  final tracker = NetworkStatusTracker();
  ref.onDispose(tracker.dispose);
  return tracker;
});

/// The shared HTTP client. Reading it when configuration is invalid is a
/// programming error: nothing may make a request in that state.
final Provider<Dio> dioProvider = Provider<Dio>((Ref ref) {
  final configuration = ref.watch(configurationResultProvider);
  final resolved = switch (configuration) {
    Success<AppConfiguration>(:final value) => value,
    Failed<AppConfiguration>() => throw StateError(
        'The HTTP client was requested while build configuration is invalid.',
      ),
  };
  final dio = buildDio(
    baseUrl: resolved.apiBaseUrl,
    defaultTimeouts: TimeoutProfile.standard,
  );
  ref.onDispose(dio.close);
  return dio;
});

/// The transport used by the refresh call ITSELF.
///
/// It attaches no credential and holds no refresh coordinator, which is what
/// makes a refresh loop structurally impossible rather than merely unlikely.
/// It also never retries: a refresh storm would be worse than a failed
/// refresh.
final Provider<ApiTransport> rawApiTransportProvider = Provider<ApiTransport>(
  (Ref ref) => DioApiTransport(
    dio: ref.watch(dioProvider),
    logger: ref.watch(loggerProvider),
    correlationIds: ref.watch(correlationIdGeneratorProvider),
    networkStatus: ref.watch(networkStatusProvider),
    clock: ref.watch(clockProvider),
    retryPolicy: RetryPolicy.none,
  ),
);

final Provider<TokenRefreshCoordinator> tokenRefreshCoordinatorProvider =
    Provider<TokenRefreshCoordinator>((Ref ref) {
  final sessions = ref.watch(sessionManagerProvider);
  final codec = ref.watch(sessionTokenCodecProvider);
  final rawClient = KararApiClient(ref.watch(rawApiTransportProvider));
  return TokenRefreshCoordinator(
    sessionManager: sessions,
    clock: ref.watch(clockProvider),
    logger: ref.watch(loggerProvider),
    refresh: (String refreshToken) async {
      try {
        final payload = await rawClient.identityRefresh(
          body: IdentityRefreshRequestDto(refreshToken: refreshToken),
          timeouts: TimeoutProfile.startup,
        );
        // The generated client now returns a typed DTO. `SessionTokenCodec` is
        // the one place a refresh payload is validated and mapped, including
        // the fallback session id the response does not repeat, so the DTO is
        // handed back as JSON rather than the codec being bypassed. Two
        // parsers for one payload is how the two drift apart.
        return codec.decode(
          payload.toJson(),
          fallbackSessionId: sessions.tokens?.sessionId,
        );
      } on ApiException catch (exception) {
        return Failed<SessionTokens>(exception.failure);
      }
    },
  );
});

/// The transport every feature uses.
final Provider<ApiTransport> apiTransportProvider = Provider<ApiTransport>(
  (Ref ref) => DioApiTransport(
    dio: ref.watch(dioProvider),
    logger: ref.watch(loggerProvider),
    correlationIds: ref.watch(correlationIdGeneratorProvider),
    networkStatus: ref.watch(networkStatusProvider),
    clock: ref.watch(clockProvider),
    sessionManager: ref.watch(sessionManagerProvider),
    refreshCoordinator: ref.watch(tokenRefreshCoordinatorProvider),
  ),
);

/// The generated client, bound to the authenticated transport.
final Provider<KararApiClient> apiClientProvider =
    Provider<KararApiClient>((Ref ref) => KararApiClient(ref.watch(apiTransportProvider)));

// ---------------------------------------------------------------------------
// Startup and routing
// ---------------------------------------------------------------------------

final Provider<BootstrapGateway> bootstrapGatewayProvider = Provider<BootstrapGateway>(
  (Ref ref) => ApiBootstrapGateway(ref.watch(apiClientProvider)),
);

final Provider<StartupCoordinator> startupCoordinatorProvider =
    Provider<StartupCoordinator>((Ref ref) {
  final coordinator = StartupCoordinator(
    loadConfiguration: () => ref.read(configurationResultProvider),
    appLock: ref.watch(appLockGateProvider),
    sessionManager: ref.watch(sessionManagerProvider),
    bootstrapGateway: ref.watch(bootstrapGatewayProvider),
    logger: ref.watch(loggerProvider),
    clock: ref.watch(clockProvider),
  );
  ref.onDispose(coordinator.dispose);
  return coordinator;
});

final Provider<StartupListenable> startupListenableProvider =
    Provider<StartupListenable>((Ref ref) {
  final listenable = StartupListenable(ref.watch(startupCoordinatorProvider));
  ref.onDispose(listenable.dispose);
  return listenable;
});

final Provider<GoRouter> routerProvider = Provider<GoRouter>((Ref ref) {
  final router = buildAppRouter(
    startup: ref.watch(startupListenableProvider),
    coordinator: ref.watch(startupCoordinatorProvider),
    screenOverrides: ref.watch(startupScreenOverridesProvider),
    featureRoutes: ref.watch(featureRoutesProvider),
    homeBuilder: ref.watch(homeScreenBuilderProvider),
  );
  ref.onDispose(router.dispose);
  return router;
});

/// Whether this binary was compiled in release mode. Used by the configuration
/// loader, which is stricter about a release build than a debug one.
bool get isReleaseBuild => kReleaseMode;

/// Loads and validates the compiled configuration.
Result<AppConfiguration> loadCompiledConfiguration({bool? releaseBuild}) =>
    const ConfigurationLoader().load(
      values: CompiledConfiguration.asMap(),
      isReleaseBuild: releaseBuild ?? kReleaseMode,
    );
