#!/usr/bin/env node
// Documentation checks — deterministic only.
//
// What this checks:
//   1. Internal markdown links: every [text](target) with a non-http target
//      must resolve to an existing file or directory relative to the doc
//      (anchors stripped). Links inside code fences and inline code are ignored.
//   2. Root README.md has a "Current phase" row matching the architecture-test
//      registry's currentPhase.
//   3. The current phase report docs/phases/phase-0N.md exists.
//   4. Every ADR referenced as [ADR-00XX] or adr/00XX-*.md in the docs exists
//      in docs/adr/.
//   5. Every direct child of modules/ has MODULE.md (shared with architecture
//      test 16; duplicated cheaply here so docs:check stands alone).
//   6. Mermaid blocks: syntactic sanity only — balanced fences, non-empty
//      blocks, first word one of the known diagram types. This deliberately
//      does NOT pretend to validate the full mermaid grammar.
//   7. docs/phases/PHASE_TEMPLATE.md carries the compliance-gate sections
//      ("Evidence produced", "SOC 2 mapping", "ISO 27001 mapping").
//   8. Emoji decoration, banned by documentation-style-guide.md §4. Detected by
//      Unicode emoji property rather than by "not ASCII", because this
//      repository documents an Arabic-first product: a not-ASCII rule would
//      flag every Arabic string, every RTL mark, and the em dashes, section
//      signs and box-drawing diagrams the house style is built on. Only
//      characters that render as colour emoji by default — or are forced to by
//      U+FE0F — are decoration. Dingbats (U+2713, U+2717) and text-presentation
//      pictographs (U+2194, U+25B6) are typography and stay legal.
//   9. AI attribution — "generated with <assistant>", "co-authored-by:
//      <assistant>" and their relatives. Style guide §4: committed documents
//      carry no tool attribution of any kind. The rule matches the attribution
//      shape, not the tool's name on its own, because branch names in this
//      repository legitimately contain one.
//  10. Generation-attribution lines — a whole line whose content is "generated
//      by/with <anything>". Tool-agnostic and line-anchored, so a sentence that
//      describes evidence "generated by the system as it runs" stays legal
//      while a trailing signature line does not.
//  11. Assistant boilerplate — "as an AI", first-person refusals, chat
//      pleasantries. A document reports; it does not converse.
//  12. Allowance liveness — every entry in STYLE_ALLOWANCES must still suppress
//      something. An allowance that has stopped matching is a hole left open
//      for the next violation, so a stale one fails the run instead of
//      lingering unnoticed.
//
// Checks 8-11 read code-stripped prose. Fenced blocks and inline code carry
// fixtures, terminal output and quoted samples, where a non-ASCII character is
// the subject rather than decoration; excluding them structurally is what makes
// the rules usable on this corpus. The cost is that they do not see inside a
// fence, which is stated here rather than discovered later.
//
// A self-test runs at the end of every invocation (or alone via --self-test):
// it seeds one violation per rule 8-12 in a temp tree, asserts each rule fires
// and names the seeded file, and asserts a set of legitimate shapes stays
// unflagged. Checks 1-7 predate it and are not covered by it.
//
// There is NO natural-language contradiction detection here — deterministic
// checks only.
//
// Zero dependencies: node: builtins only.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  childDirs,
  ensureOutDir,
  EXCLUDED_DIRS,
  readJson,
  readText,
  walkFiles,
} from './lib/util.mjs';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..', '..');
const REGISTRY_REL = path.join('docs', 'testing', 'architecture-test-registry.json');

const MERMAID_TYPES = new Set([
  'graph',
  'flowchart',
  'sequenceDiagram',
  'stateDiagram-v2',
  'classDiagram',
  'erDiagram',
]);

const MD_EXTS = new Set(['.md']);

// ---------------------------------------------------------------------------
// Prohibited decoration (checks 8-11), from docs/documentation-style-guide.md §4
// ---------------------------------------------------------------------------

// Emoji, by Unicode property. `Emoji_Presentation` is the discriminating one:
// it holds exactly the characters a renderer draws as colour emoji with no
// variation selector, which is what separates U+2705 from U+2713, U+2194 and
// U+25B6 — text symbols this repository uses as typography.
const EMOJI_RULES = [
  { label: 'default emoji presentation', re: /\p{Emoji_Presentation}/gu },
  { label: 'emoji presentation selector U+FE0F', re: /\p{Extended_Pictographic}\uFE0F/gu },
  { label: 'regional indicator (flag sequence)', re: /\p{Regional_Indicator}/gu },
  { label: 'skin-tone modifier', re: /\p{Emoji_Modifier}/gu },
  { label: 'keycap sequence', re: /[0-9#*]\uFE0F?\u20E3/gu },
];

// Assistants and generation tools, as they are named in an attribution. Kept as
// one alternation so every attribution shape below recognises the same set.
const ASSISTANT =
  '(?:claude(?:\\s+code)?|chatgpt|gpt-?[0-9o]+|copilot|cursor|codeium|windsurf|devin|gemini|codex|bard|an?\\s+ai|ai\\s+(?:assistant|agent|model|tool)|an?\\s+(?:large\\s+)?language\\s+model|an?\\s+llm)';

// Attribution shapes. Each must name the assistant, because the tool names on
// their own are ordinary words here: branch names such as
// `claude/karar-v2-phase-1-foundation` appear throughout the phase reports.
const AI_ATTRIBUTION_RULES = [
  {
    label: 'generated/created/written by an assistant',
    re: new RegExp(
      `\\b(?:generated|created|written|authored|produced|drafted|built)\\s+(?:with|by|using)\\s+(?:the\\s+)?${ASSISTANT}\\b`,
      'gi',
    ),
  },
  {
    label: 'assistant co-author trailer',
    re: new RegExp(`\\bco-?authored-by:\\s*[^\\n]*?${ASSISTANT}\\b`, 'gi'),
  },
  {
    label: 'assistance credited to an assistant',
    re: new RegExp(
      `\\bwith\\s+(?:the\\s+)?(?:assistance|help|aid)\\s+(?:of|from)\\s+(?:the\\s+)?${ASSISTANT}\\b`,
      'gi',
    ),
  },
  {
    label: 'assistant credited as the author',
    re: new RegExp(
      `\\b${ASSISTANT}\\s+(?:wrote|generated|produced|created|authored)\\s+(?:this|these|the)\\b`,
      'gi',
    ),
  },
];

// A generation-attribution *line*: the whole line, once markdown decoration is
// peeled off, is a statement about what produced the document. Line-anchoring
// is the whole point — "evidence generated by the system as it runs" is a fact
// about a control and must stay sayable.
const GENERATED_LINE_RULES = [
  { label: 'generation attribution', re: /^(?:auto-?)?generated\s+(?:with|by|using)\b/i },
  {
    label: 'generation disclaimer',
    re: /^this\s+(?:file|document|page|report|section)\s+(?:is|was)\s+(?:auto(?:matically)?-?\s*)?generated\b/i,
  },
  { label: 'do-not-edit banner', re: /^do\s+not\s+edit\b.*\bgenerated\b/i },
];

// Assistant narration. The first-person rules are case-sensitive and exclude
// "Type I", the one place a bare capital I legitimately precedes a verb here.
const BOILERPLATE_RULES = [
  { label: 'assistant self-reference', re: /\bas an ai\b/gi },
  { label: 'assistant self-reference', re: /\bas a large language model\b/gi },
  { label: 'assistant self-reference', re: /\bi am an ai\b/gi },
  {
    label: 'first-person refusal',
    re: /(?<!\bType )\bI\s+(?:cannot|can't|can not|am unable to|do not have|don't have)\b/g,
  },
  {
    label: 'first-person work report',
    re: /(?<!\bType )\bI(?:'ve|'ll| have| will)\s+(?:updated|created|added|implemented|fixed|refactored|generated|written|removed)\b/g,
  },
  { label: 'chat pleasantry', re: /\b(?:i )?hope (?:this|that) helps\b/gi },
  { label: 'chat pleasantry', re: /\blet me know if you\b/gi },
  {
    label: 'chat pleasantry',
    re: /\bfeel free to (?:ask|reach out|let me know|modify|adjust)\b/gi,
  },
  { label: 'chat pleasantry', re: /\b(?:happy|glad) to help\b/gi },
  { label: 'chat opener', re: /\b(?:certainly|absolutely|sure thing)[!,]\s/gi },
  {
    label: 'chat handoff',
    re: /\bhere(?:'s| is) (?:the|a|your) (?:updated|revised|complete|full|final|new)\b/gi,
  },
  { label: 'chat handoff', re: /\bas (?:requested|per your request)\b/gi },
  { label: 'apology', re: /(?<!\bType )\bI apologi[sz]e\b/g },
];

// Narrow, per-occurrence allowances. An entry names one file, one check, and
// the exact text a hit must fall inside. There is deliberately no path glob and
// no whole-file exemption: a suppression wide enough to be convenient is wide
// enough to hide the next violation. Check 12 fails the run when an entry stops
// matching, so the list cannot outlive its reason.
const STYLE_ALLOWANCES = [
  {
    file: 'docs/legacy/qarar-audit.md',
    check: 'no-assistant-boilerplate',
    quote: 'I cannot also be the independent assessor of my own work',
    reason:
      "Verbatim quotation of the legacy system's own audit worklist. The first person is the legacy auditor, not this repository, and editing a quotation to satisfy a style rule would falsify the evidence the audit rests on.",
  },
  {
    file: 'docs/legacy/security-findings.md',
    check: 'no-assistant-boilerplate',
    quote: 'I cannot also be the independent assessor of my own work',
    reason:
      'The same legacy quotation, cited a second time as the source of finding 3. Quoted source evidence is reproduced as found.',
  },
];

function relTo(root, file) {
  return path.relative(root, file);
}

function rel(file) {
  return relTo(REPO_ROOT, file);
}

function mdFiles() {
  return walkFiles(REPO_ROOT, { exts: MD_EXTS });
}

/**
 * Blank out fenced code blocks and inline code spans, preserving the line
 * structure so reported line numbers match the file.
 */
function stripMarkdownCode(markdown) {
  const lines = markdown.split('\n');
  const out = [];
  let fenceLen = 0; // 0 = not in a fence
  for (const line of lines) {
    const m = line.match(/^\s*(`{3,})(.*)$/);
    if (m) {
      const ticks = m[1].length;
      if (fenceLen === 0) {
        fenceLen = ticks;
        out.push('');
        continue;
      }
      if (ticks >= fenceLen && m[2].trim() === '') {
        fenceLen = 0;
        out.push('');
        continue;
      }
      out.push('');
      continue;
    }
    if (fenceLen > 0) {
      out.push('');
      continue;
    }
    out.push(line.replace(/`[^`]*`/g, (s) => ' '.repeat(s.length)));
  }
  return out;
}

function targetExists(docFile, rawTarget) {
  let target = rawTarget.trim();
  if (target.startsWith('<') && target.endsWith('>')) target = target.slice(1, -1);
  // Drop an optional trailing markdown title: (path "Title")
  target = target.replace(/\s+["'][^"']*["']$/, '');
  const [pathPart] = target.split('#');
  const clean = pathPart.split('?')[0];
  if (clean === '') return true; // pure anchor
  let decoded = clean;
  try {
    decoded = decodeURIComponent(clean);
  } catch {
    /* keep raw */
  }
  const resolved = decoded.startsWith('/')
    ? path.join(REPO_ROOT, decoded)
    : path.resolve(path.dirname(docFile), decoded);
  return fs.existsSync(resolved);
}

function isExternal(target) {
  return /^(https?:\/\/|mailto:|tel:|data:|javascript:|#)/i.test(target.trim());
}

function checkLinks(files) {
  const problems = [];
  const linkRe = /!?\[[^\]]*\]\(([^()\s]+(?:\s+"[^"]*")?)\)/g;
  const refDefRe = /^\s*\[[^\]]+\]:\s+(\S+)/;
  for (const file of files) {
    const lines = stripMarkdownCode(readText(file));
    lines.forEach((line, i) => {
      for (const m of line.matchAll(linkRe)) {
        const target = m[1];
        if (isExternal(target)) continue;
        if (!targetExists(file, target)) {
          problems.push(`${rel(file)}:${i + 1} broken link '${target}'`);
        }
      }
      const def = line.match(refDefRe);
      if (def && !isExternal(def[1]) && !targetExists(file, def[1])) {
        problems.push(`${rel(file)}:${i + 1} broken reference definition '${def[1]}'`);
      }
    });
  }
  return problems;
}

// PHASE STATUS MUST AGREE ACROSS EVERY DOCUMENT THAT STATES IT.
//
// A commit whose entire purpose was to stop claiming Phase 4 was COMPLETE
// updated three documents and left five others saying COMPLETE — including
// `docs/roadmap.md`, the canonical phase table, and a prose block in the same
// README whose status block had just been corrected. Every individual document
// was internally coherent; nothing compared them, so nothing failed.
//
// This reads the current phase and its status from the README status block,
// then requires that no other tracked document contradicts it. It deliberately
// checks only the CURRENT phase: earlier phases are settled history and later
// ones are not claimed yet.
/**
 * Documents that contradict a fact the tree can be asked about.
 *
 * `docs:check` was green while `docs/phases/phase-05.md` said a statement could
 * not be chosen on a device — twenty lines from its own deliverables table
 * saying the picker was built — and while the architecture registry said
 * modules held no code, beside 484 module source files. A green documentation
 * gate that cannot see either of those is not a documentation gate.
 *
 * Only facts a machine can DERIVE are pinned here, and each rule names the
 * artifact it derives from. This is deliberately not a prose parser: it asks a
 * small number of yes/no questions of the source and refuses a document that
 * answers them differently.
 */
function checkDerivedFacts() {
  const problems = [];
  const read = (rel) => {
    const full = path.join(REPO_ROOT, rel);
    return fs.existsSync(full) ? fs.readFileSync(full, 'utf8') : null;
  };
  const countFiles = (dir, filter) => {
    const root = path.join(REPO_ROOT, dir);
    if (!fs.existsSync(root)) return 0;
    let n = 0;
    const walk = (d) => {
      for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
        const full = path.join(d, entry.name);
        if (entry.isDirectory()) {
          if (EXCLUDED_DIRS.has(entry.name) || entry.name === '__tests__') continue;
          walk(full);
        } else if (filter(full)) n += 1;
      }
    };
    walk(root);
    return n;
  };

  // A. The pure-package list in the docs must match the executable checker.
  const runner = read('scripts/checks/architecture.mjs');
  if (runner === null) {
    problems.push('scripts/checks/architecture.mjs missing — the pure-package fact cannot be derived');
  } else {
    const block = /const PURE_PACKAGES = \[([\s\S]*?)\];/.exec(runner);
    if (block === null) {
      problems.push('architecture.mjs has no parseable PURE_PACKAGES — this rule is now blind');
    } else {
      const actual = [...block[1].matchAll(/'([\w-]+)'/g)].map((m) => m[1]);
      const WORDS = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight'];
      const expected = WORDS[actual.length] ?? String(actual.length);
      for (const rel of ['docs/testing/architecture-test-registry.json', 'docs/testing/architecture-tests.md']) {
        const text = read(rel);
        if (text === null) continue;
        for (const word of WORDS) {
          if (word === expected) continue;
          const stale = new RegExp(`the ${word} pure packages`, 'i');
          if (stale.test(text)) {
            problems.push(
              `${rel} says "the ${word} pure packages"; the checker declares ${actual.length} (${actual.join(', ')})`,
            );
          }
        }
      }
    }
  }

  // B. The registry must not claim modules are empty while they hold code.
  const moduleSources = countFiles('modules', (f) => f.endsWith('.ts') && !f.endsWith('.test.ts'));
  const registryText = read('docs/testing/architecture-test-registry.json');
  if (registryText !== null && moduleSources > 0) {
    for (const claim of ['no module code', 'modules have no code', 'no TypeScript in modules']) {
      if (registryText.toLowerCase().includes(claim)) {
        problems.push(
          `architecture-test-registry.json says "${claim}" while modules/ holds ${moduleSources} production files`,
        );
      }
    }
  }

  // C. The phase report must not deny a picker that is registered.
  const androidPicker = read('apps/mobile/android/app/src/main/kotlin/com/kararfinance/app/StatementDocumentPicker.kt');
  const iosPicker = read('apps/mobile/ios/Runner/StatementDocumentPicker.swift');
  // Every document a reader consults for current state, not just the phase
  // report: the contradiction recurred across four of them last time.
  const CURRENT_STATE_DOCS = [
    'docs/phases/phase-05.md',
    'README.md',
    'apps/mobile/README.md',
    'docs/roadmap.md',
    'docs/onboarding/developer.md',
    'docs/onboarding/flutter.md',
    'docs/architecture/flutter.md',
    'docs/architecture/backend.md',
    'docs/architecture/overview.md',
    'docs/phases/README.md',
  ];
  const phase = read('docs/phases/phase-05.md');
  if (androidPicker !== null && iosPicker !== null) {
    for (const rel of CURRENT_STATE_DOCS) {
      const text = read(rel);
      if (text === null) continue;
      for (const claim of [
        'no file picker adapter',
        'cannot be chosen on a device',
        'no picker adapter ships',
        'picker port with no adapter',
        // The deferred-work list said this and rules C/D did not know the
        // words. Every phrase here was found in the tree, not imagined.
        'picker port with no implementation',
        'nobody can choose a file',
      ]) {
        if (text.toLowerCase().includes(claim)) {
          problems.push(`${rel} says "${claim}" while both native picker implementations exist`);
        }
      }
    }
  }

  // D. The phase report must not deny work whose invocation is in the source.
  const manual = read('modules/transactions/application/use-cases/create-manual-transaction.ts') ?? '';
  const csv = read('modules/statement-imports/application/use-cases/commit-statement-import.ts') ?? '';
  if (phase !== null) {
    if (manual.includes('merchantRules.evaluate') && csv.includes('this.categories.match')) {
      for (const rel of CURRENT_STATE_DOCS) {
        const text = read(rel);
        if (text === null) continue;
        for (const claim of [
          'nothing applies merchant rules',
          'categorization is assignment, not a pipeline',
          'merchant rules are schema and domain; nothing applies them',
        ]) {
          if (text.toLowerCase().includes(claim)) {
            problems.push(`${rel} says "${claim}" while both write paths invoke the evaluator`);
          }
        }
      }
    }
    if (manual.includes('suggestTransfersFor') && csv.includes('suggestTransfersFor')) {
      for (const claim of ['suggestion is not', 'nothing calls it']) {
        if (phase.toLowerCase().includes(claim)) {
          problems.push(
            `docs/phases/phase-05.md says "${claim}" while both write paths trigger suggestion generation`,
          );
        }
      }
    }
  }

  // E. A module whose use cases the API app wires, and which holds production
  // code, may not have documentation saying it has neither.
  //
  // This is the shape the staleness actually took: six MODULE.md files and
  // three layer READMEs said "no transport layer exists yet" long after the
  // routes were mounted and driven by the conformance suite. Rules C and D
  // could not see it -- they match fixed phrases in a fixed file list, and
  // these were different words in different files.
  //
  // Both halves are derived per MODULE, never globally: the skeleton modules
  // say "no application code exists yet" and are telling the truth, so a rule
  // keyed on whether the FINANCIAL app has controllers would flag all of them.
  const composition = read('apps/api/src/composition/phase5-modules.ts') ?? '';
  const wired = new Set(
    [...composition.matchAll(/@karar\/([a-z-]+)/g)]
      .map((m) => m[1])
      .filter((name) => fs.existsSync(path.join(REPO_ROOT, 'modules', name))),
  );
  const TRANSPORT_DENIALS = [
    'no transport layer exists yet',
    'no transport layer and no',
    'no http surface and no controller exist',
    'no ingestion endpoint and no transport layer exist',
    'no transport exists for this module yet',
    'there is no http surface here',
    'no transport, no ingestion',
    'neither is a running path',
  ];
  const EMPTINESS_DENIALS = ['no application code exists yet', 'this directory is a skeleton'];
  for (const rel of walkFiles(path.join(REPO_ROOT, 'modules'), { exts: MD_EXTS })
    .map((f) => path.relative(REPO_ROOT, f))) {
    // modules/README.md sits directly under modules/ and names no module.
    const moduleName = rel.split(path.sep)[1];
    if (moduleName === undefined) continue;
    if (!fs.existsSync(path.join(REPO_ROOT, 'modules', moduleName, 'MODULE.md'))) continue;
    const text = read(rel);
    if (text === null) continue;
    const lower = text.toLowerCase();
    if (wired.has(moduleName)) {
      for (const denial of TRANSPORT_DENIALS) {
        if (lower.includes(denial)) {
          problems.push(
            `${rel} says "${denial}" while apps/api/src/composition/phase5-modules.ts wires @karar/${moduleName} and mounts its routes`,
          );
        }
      }
    }
    // An emptiness claim is judged against the directory the document sits in,
    // not against its module: a layer README that says "this directory is a
    // skeleton" is describing its own layer, and several modules have layers
    // that are genuinely still empty next to layers that are not.
    const ownDir = path.dirname(rel);
    const ownSourceCount = countFiles(
      ownDir,
      (f) => f.endsWith('.ts') && !f.endsWith('.test.ts'),
    );
    if (ownSourceCount > 0) {
      for (const denial of EMPTINESS_DENIALS) {
        if (lower.includes(denial)) {
          problems.push(
            `${rel} says "${denial}" while ${ownDir} holds ${ownSourceCount} production files`,
          );
        }
      }
    }
  }

  // F. No current-state document may deny a Flutter financial surface that
  // exists. Three of them did, including one that contradicted itself ten
  // lines later.
  const featuresDir = path.join(REPO_ROOT, 'apps', 'mobile', 'lib', 'features');
  const financialFeatures = fs.existsSync(featuresDir)
    ? fs
        .readdirSync(featuresDir, { withFileTypes: true })
        .filter((e) => e.isDirectory())
        .map((e) => e.name)
        .filter((n) => /^(financial_|payment_|statement_|transaction|transfer_)/.test(n))
    : [];
  if (financialFeatures.length > 0) {
    for (const rel of CURRENT_STATE_DOCS) {
      const text = read(rel);
      if (text === null) continue;
      const lower = text.toLowerCase();
      for (const claim of [
        'any flutter financial surface',
        'not built: any flutter surface',
        'no flutter financial surface',
      ]) {
        const at = lower.indexOf(claim);
        if (at < 0) continue;
        // Only a DENIAL is a problem. The same words appear in sentences that
        // describe what was built, so the preceding clause decides.
        const before = lower.slice(Math.max(0, at - 60), at);
        if (/not built|does not exist|no |never/.test(before)) {
          problems.push(
            `${rel} denies a Flutter financial surface while apps/mobile/lib/features holds ${financialFeatures.length} of them (${financialFeatures.join(', ')})`,
          );
        }
      }
    }
  }

  return problems;
}

function checkPhaseStatusConsistency(files) {
  const problems = [];
  const readmePath = path.join(REPO_ROOT, 'README.md');
  if (!fs.existsSync(readmePath)) return ['README.md missing'];
  const readme = fs.readFileSync(readmePath, 'utf8');

  const status = readme.match(/\|\s*Current phase\s*\|\s*\*\*([0-9.]+)\s*[—-]\s*([A-Z ]+?)\*\*/);
  if (!status) {
    return ['README.md has no parseable "Current phase" row; every other check here depends on it'];
  }
  const [, phase, declared] = [status[0], status[1], status[2].trim()];

  // Only a claim of completion is a contradiction. "IN PROGRESS" elsewhere is
  // agreement, and a document may legitimately not mention the phase at all.
  if (declared === 'COMPLETE') return problems;

  const claim = new RegExp(
    `Phase ${phase.replace('.', '\\.')}\\b[^.\n]{0,80}?\\b(?:is |was |—\\s*)?COMPLETE\\b` +
      `|Phase ${phase.replace('.', '\\.')}\\b[^.\n]{0,80}?\\bis complete\\b` +
      `|\\bPhase ${phase.replace('.', '\\.')} delivered\\b`,
    'i',
  );

  for (const file of files) {
    const relative = path.relative(REPO_ROOT, file);
    // Phase reports for EARLIER phases are historical records and correctly
    // describe their own phase as complete.
    if (/docs\/phases\/phase-0(?!4)/.test(relative)) continue;
    // The compliance corpus is a dated gate snapshot; it scopes its own claims.
    if (relative.startsWith('docs/compliance/')) continue;

    const text = fs.readFileSync(file, 'utf8');
    text.split('\n').forEach((line, index) => {
      // A line that states what COMPLETE would mean, or denies completion, is
      // not a claim of it.
      if (/does not mean|will mean|not complete|NOT a closeout|is NOT complete/i.test(line)) return;

      // A TABLE ROW states the phase in one cell and its status in another, so
      // no "Phase 4 ... COMPLETE" prose pattern can ever match it. That is the
      // exact shape the canonical roadmap table uses, and the exact shape that
      // survived the correction it was supposed to receive.
      const cells = line.startsWith('|') ? line.split('|').map((c) => c.trim()) : null;
      const isPhaseRow = cells !== null && cells.some((c) => c.replace(/\*/g, '').trim() === phase);
      if (isPhaseRow && /\bCOMPLETE\b/.test(line)) {
        problems.push(
          `${relative}:${index + 1} is a table row for phase ${phase} marked COMPLETE, ` +
            `but README declares it ${declared}.`,
        );
        return;
      }

      if (claim.test(line)) {
        problems.push(
          `${relative}:${index + 1} says Phase ${phase} is COMPLETE, but README declares it ${declared}. ` +
            'A status stated in more than one place has to agree in all of them.',
        );
      }
    });
  }
  return problems;
}

function checkReadmePhase(registry) {
  const problems = [];
  const readmePath = path.join(REPO_ROOT, 'README.md');
  if (!fs.existsSync(readmePath)) return ['README.md missing'];
  const row = readText(readmePath)
    .split('\n')
    .find((l) => /^\|\s*Current phase\s*\|/i.test(l));
  if (!row) {
    problems.push(`README.md: no '| Current phase |' row`);
    return problems;
  }
  const value = row.split('|')[2] ?? '';
  const num = value.match(/(\d+(?:\.\d+)?)/);
  if (!num) {
    problems.push(`README.md: 'Current phase' row carries no phase number ('${value.trim()}')`);
  } else if (Number(num[1]) !== registry.currentPhase) {
    problems.push(
      `README.md: 'Current phase' says ${num[1]} but ${REGISTRY_REL} says ${registry.currentPhase}`,
    );
  }
  return problems;
}

function phaseReportName(phase) {
  const intPart = Math.floor(phase);
  const padded = String(intPart).padStart(2, '0');
  // Fractional phases use a dash, not a dot, in the filename (the canonical
  // Phase 3.5 report is docs/phases/phase-03-5.md).
  const frac = phase === intPart ? '' : `-${String(phase).split('.')[1]}`;
  return `phase-${padded}${frac}.md`;
}

function checkPhaseReport(registry) {
  const name = phaseReportName(registry.currentPhase);
  const full = path.join(REPO_ROOT, 'docs', 'phases', name);
  return fs.existsSync(full)
    ? []
    : [`docs/phases/${name} missing for currentPhase ${registry.currentPhase}`];
}

function checkAdrReferences(files) {
  const problems = [];
  const adrDir = path.join(REPO_ROOT, 'docs', 'adr');
  const adrFiles = fs.existsSync(adrDir) ? fs.readdirSync(adrDir) : [];
  const exists = (num) => adrFiles.some((f) => f.startsWith(`${num}-`) && f.endsWith('.md'));
  const seen = new Set();
  for (const file of files) {
    const lines = stripMarkdownCode(readText(file));
    lines.forEach((line, i) => {
      const refs = [
        ...line.matchAll(/\[ADR-(\d{4})\]/g),
        ...line.matchAll(/\badr\/(\d{4})-[A-Za-z0-9-]*\.md/g),
      ];
      for (const m of refs) {
        const key = `${rel(file)}:${i + 1}:${m[1]}`;
        if (seen.has(key)) continue;
        seen.add(key);
        if (!exists(m[1])) {
          problems.push(`${rel(file)}:${i + 1} references ADR ${m[1]}, absent from docs/adr/`);
        }
      }
    });
  }
  return problems;
}

function checkModuleDocs() {
  const problems = [];
  for (const mod of childDirs(path.join(REPO_ROOT, 'modules'))) {
    if (!fs.existsSync(path.join(REPO_ROOT, 'modules', mod, 'MODULE.md'))) {
      problems.push(`modules/${mod}: MODULE.md missing`);
    }
  }
  return problems;
}

function checkMermaid(files) {
  const problems = [];
  for (const file of files) {
    const lines = readText(file).split('\n');
    let fenceLen = 0;
    let isMermaid = false;
    let block = [];
    let openLine = 0;
    lines.forEach((line, i) => {
      const m = line.match(/^\s*(`{3,})(.*)$/);
      if (m) {
        const ticks = m[1].length;
        const rest = m[2].trim();
        if (fenceLen === 0) {
          fenceLen = ticks;
          isMermaid = rest.split(/\s+/)[0] === 'mermaid';
          block = [];
          openLine = i + 1;
          return;
        }
        if (ticks >= fenceLen && rest === '') {
          if (isMermaid) {
            const content = block.filter((l) => l.trim() !== '' && !l.trim().startsWith('%%'));
            if (content.length === 0) {
              problems.push(`${rel(file)}:${openLine} empty mermaid block`);
            } else {
              const first = content[0].trim().split(/\s+/)[0];
              if (!MERMAID_TYPES.has(first)) {
                problems.push(
                  `${rel(file)}:${openLine} mermaid block starts with '${first}' — expected one of ${[...MERMAID_TYPES].join('|')}`,
                );
              }
            }
          }
          fenceLen = 0;
          isMermaid = false;
          return;
        }
        block.push(line);
        return;
      }
      if (fenceLen > 0) block.push(line);
    });
    if (fenceLen > 0) {
      problems.push(`${rel(file)}: unbalanced code fence (opened line ${openLine}, never closed)`);
    }
  }
  return problems;
}

function checkPhaseTemplate() {
  const templatePath = path.join(REPO_ROOT, 'docs', 'phases', 'PHASE_TEMPLATE.md');
  if (!fs.existsSync(templatePath)) return ['docs/phases/PHASE_TEMPLATE.md missing'];
  const content = readText(templatePath);
  const problems = [];
  for (const section of ['Evidence produced', 'SOC 2 mapping', 'ISO 27001 mapping']) {
    if (!new RegExp(`^##\\s+${section}\\s*$`, 'm').test(content)) {
      problems.push(
        `docs/phases/PHASE_TEMPLATE.md: missing '## ${section}' section (compliance-gate wiring)`,
      );
    }
  }
  return problems;
}

// ---------------------------------------------------------------------------
// Checks 8-12: prohibited decoration in documentation prose
// ---------------------------------------------------------------------------

/** Codepoint label for a match, e.g. "U+2705" or "U+26A0 U+FE0F". */
function codepointsOf(text) {
  return [...text]
    .map((c) => `U+${c.codePointAt(0).toString(16).toUpperCase().padStart(4, '0')}`)
    .join(' ');
}

/**
 * True when `hit` sits inside an occurrence of an allowance's exact quote on
 * the same line of the same file. Span containment, not a line- or file-level
 * pass: a second violation elsewhere on the same line still fails.
 */
function isAllowed(allowance, relFile, checkName, line, start, end) {
  if (allowance.file !== relFile || allowance.check !== checkName) return false;
  for (let from = 0; ;) {
    const at = line.indexOf(allowance.quote, from);
    if (at === -1) return false;
    if (start >= at && end <= at + allowance.quote.length) return true;
    from = at + 1;
  }
}

/**
 * Run `rules` over the code-stripped prose of every file, dropping hits an
 * allowance covers. `describe` turns a hit into the problem line. Returns
 * { problems, usedAllowances }.
 */
function scanProse(files, root, checkName, rules, describe) {
  const problems = [];
  const used = new Set();
  for (const file of files) {
    const relFile = relTo(root, file);
    const lines = stripMarkdownCode(readText(file));
    lines.forEach((line, i) => {
      for (const { label, re } of rules) {
        for (const m of line.matchAll(re)) {
          const start = m.index;
          const end = start + m[0].length;
          const allowance = STYLE_ALLOWANCES.find((a) =>
            isAllowed(a, relFile, checkName, line, start, end),
          );
          if (allowance) {
            used.add(STYLE_ALLOWANCES.indexOf(allowance));
            continue;
          }
          problems.push(describe({ relFile, line: i + 1, label, text: m[0] }));
        }
      }
    });
  }
  return { problems, usedAllowances: used };
}

function checkEmoji(files, root) {
  return scanProse(
    files,
    root,
    'no-emoji',
    EMOJI_RULES,
    ({ relFile, line, label, text }) =>
      `${relFile}:${line} emoji ${codepointsOf(text)} (${label}) — the style guide bans emoji in documentation; a status icon becomes a word: PASS, FAIL, COMPLETE, PENDING, WARNING`,
  );
}

function checkAiAttribution(files, root) {
  return scanProse(
    files,
    root,
    'no-ai-attribution',
    AI_ATTRIBUTION_RULES,
    ({ relFile, line, label, text }) =>
      `${relFile}:${line} AI attribution '${text.trim()}' (${label}) — a committed document names the team that owns it, not the tool that touched it`,
  );
}

/**
 * Strip the markdown decoration a signature line hides behind — list markers,
 * blockquote markers, emphasis, small-text tags, horizontal-rule dashes — so
 * the anchor sees the sentence itself.
 */
function undecorate(line) {
  return line
    .replace(/<\/?(?:sub|sup|small|em|strong|i|b)>/gi, '')
    .replace(/^[\s>*_~-]+/, '')
    .replace(/[\s*_~]+$/, '')
    .trim();
}

function checkGeneratedByLine(files, root) {
  const problems = [];
  const used = new Set();
  for (const file of files) {
    const relFile = relTo(root, file);
    const lines = stripMarkdownCode(readText(file));
    lines.forEach((raw, i) => {
      const line = undecorate(raw);
      if (line === '') return;
      for (const { label, re } of GENERATED_LINE_RULES) {
        if (!re.test(line)) continue;
        // A line-level rule takes a line-level allowance: the quote must be the
        // whole undecorated line, so an allowance cannot be widened by adding
        // text around the sentence it was written for.
        const allowance = STYLE_ALLOWANCES.find(
          (a) => a.file === relFile && a.check === 'no-generated-by-line' && a.quote === line,
        );
        if (allowance) {
          used.add(STYLE_ALLOWANCES.indexOf(allowance));
          continue;
        }
        problems.push(
          `${relFile}:${i + 1} ${label} '${line}' — a document states what it is, not what produced it`,
        );
      }
    });
  }
  return { problems, usedAllowances: used };
}

function checkAssistantBoilerplate(files, root) {
  return scanProse(
    files,
    root,
    'no-assistant-boilerplate',
    BOILERPLATE_RULES,
    ({ relFile, line, label, text }) =>
      `${relFile}:${line} assistant boilerplate '${text.trim()}' (${label}) — documentation reports in the team's voice; it does not converse`,
  );
}

/**
 * Every allowance must still suppress a real hit. A suppression that no longer
 * suppresses anything has become an unexamined exemption, so it fails here
 * rather than sitting in the list until something new slips under it.
 */
function checkAllowancesLive(usedIndexes) {
  const problems = [];
  STYLE_ALLOWANCES.forEach((a, i) => {
    if (usedIndexes.has(i)) return;
    problems.push(
      `allowance ${i + 1} (${a.file}, ${a.check}, '${a.quote}') matched nothing — delete it, or restore the text it was written for`,
    );
  });
  return problems;
}

/** Run checks 8-11 over one file set and fold their allowance usage together. */
function runStyleChecks(files, root) {
  const emoji = checkEmoji(files, root);
  const attribution = checkAiAttribution(files, root);
  const generated = checkGeneratedByLine(files, root);
  const boilerplate = checkAssistantBoilerplate(files, root);
  const used = new Set([
    ...emoji.usedAllowances,
    ...attribution.usedAllowances,
    ...generated.usedAllowances,
    ...boilerplate.usedAllowances,
  ]);
  return {
    checks: [
      { name: 'no-emoji', problems: emoji.problems },
      { name: 'no-ai-attribution', problems: attribution.problems },
      { name: 'no-generated-by-line', problems: generated.problems },
      { name: 'no-assistant-boilerplate', problems: boilerplate.problems },
      { name: 'style-allowances-live', problems: checkAllowancesLive(used) },
    ],
  };
}

// ---------------------------------------------------------------------------
// Self-test: seed one violation per style rule in a temp tree and assert every
// rule fails on it and names it, and that a set of legitimate shapes stays
// unflagged. Runs at the end of every normal invocation so a passing run is
// evidence the rules can still fail.
// ---------------------------------------------------------------------------

// Written as escapes so this file stays pure ASCII: a check that forbids emoji
// in documentation has no business carrying emoji in its own source.
const SEED = {
  checkMark: '\u2705', // WHITE HEAVY CHECK MARK — colour emoji by default
  warningVs16: '\u26A0\uFE0F', // WARNING SIGN + VS16 — text symbol forced to emoji
  dingbatCheck: '\u2713', // CHECK MARK — a dingbat, legal
  dingbatX: '\u2717', // BALLOT X — a dingbat, legal
  leftRight: '\u2194', // LEFT RIGHT ARROW — pictographic, text presentation, legal
  play: '\u25B6', // BLACK RIGHT-POINTING TRIANGLE — same, legal
  emDash: '\u2014',
  middot: '\u00B7',
  rlm: '\u200F', // RIGHT-TO-LEFT MARK
  lrm: '\u200E', // LEFT-TO-RIGHT MARK
  arabic: '\u0627\u0644\u0645\u0646\u0635\u0629', // "the platform"
};

// Allowance-dependent cases read the live list, and only by the file an entry
// names — never by list position. Deleting an allowance once its reason expires
// therefore retires its cases with it rather than breaking the self-test, which
// is the point: an allowance is meant to be removable.
const ALLOWED_FILE = 'docs/legacy/qarar-audit.md';
const STALE_FILE = 'docs/legacy/security-findings.md';
const ALLOWED_ENTRY = STYLE_ALLOWANCES.find(
  (a) => a.file === ALLOWED_FILE && a.check === 'no-assistant-boilerplate',
);
const STALE_ENTRY = STYLE_ALLOWANCES.find((a) => a.file === STALE_FILE);

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&');

function buildSelfTestFixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'karar-docs-selftest-'));
  const write = (relPath, content) => {
    const full = path.join(root, relPath);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  };

  write(
    'docs/seed-emoji.md',
    `# Seed\n\n| Check | Status |\n|---|---|\n| Links | ${SEED.checkMark} |\n`,
  );
  write('docs/seed-emoji-vs16.md', `# Seed\n\n${SEED.warningVs16} Rotation is overdue.\n`);
  write(
    'docs/seed-attribution.md',
    `# Seed\n\nThis runbook was written by Claude Code in one pass.\n`,
  );
  write('docs/seed-generated.md', `# Seed\n\nContent.\n\n_Generated by some-doc-tool v3_\n`);
  write('docs/seed-boilerplate.md', `# Seed\n\nAs an AI, I cannot verify the residency claim.\n`);

  // The allowance is scoped to one path. The same quotation in a second file is
  // still a violation, which is what keeps the allowance from becoming a rule.
  if (ALLOWED_ENTRY) {
    write(ALLOWED_FILE, `# Legacy\n\nThe worklist states: *"${ALLOWED_ENTRY.quote}."*\n`);
    write('docs/legacy/other-quote.md', `# Elsewhere\n\n*"${ALLOWED_ENTRY.quote}."*\n`);
  }
  // STALE_FILE is deliberately never written, so the allowance that names it has
  // nothing to suppress and check 12 has something real to report.

  // A nested checkout (a linked worktree's `.git` is a FILE, not a directory)
  // and an agent scratch tree. Both carry a real violation, and neither may be
  // scanned: otherwise every "scanned: N" figure this project publishes as
  // evidence depends on who happens to have an agent running, and a check that
  // requires a file to be PRESENT can be satisfied by a copy of some other
  // commit rather than by this tree.
  write('nested-checkout/.git', 'gitdir: /elsewhere/.git/worktrees/nested\n');
  write('nested-checkout/docs/nested.md', '# Nested\n\nAs an AI, I cannot verify this.\n');
  write('.claude/worktrees/agent-x/docs/agent.md', '# Agent\n\nAs an AI, I cannot verify this.\n');

  // Legitimate shapes, all in one file: none of them may raise a problem.
  write(
    'docs/clean.md',
    [
      '# Clean',
      '',
      `**Status:** ACCEPTED ${SEED.middot} **Phase:** 4 ${SEED.middot} Arabic-first ${SEED.emDash} ${SEED.arabic}.`,
      `Bidi marks in a worked example: ${SEED.rlm}${SEED.arabic}${SEED.lrm} renders right to left.`,
      `Mapping: domain objects ${SEED.leftRight} persistence models. State: PROPOSED ${SEED.play} MIGRATED.`,
      `Manual tick sheet: ${SEED.dingbatCheck} accepted, ${SEED.dingbatX} rejected.`,
      'Frequencies include `continuous` (generated by the system as it runs).',
      'A **Type I** report says the controls were suitably designed at a point in time.',
      'The branch is `claude/karar-v2-phase-1-foundation`, merged through PR #6.',
      'Style rule: no AI signatures, no "Generated with ..." lines, no tool attribution.',
      '',
      '```text',
      `Sample terminal output: ${SEED.checkMark} 12 passed`,
      'Generated with some-tool',
      '```',
      '',
      `Inline sample: \`${SEED.checkMark}\` is the codepoint under discussion.`,
      '',
    ].join('\n'),
  );

  return root;
}

// Each case: the check must fail, and one of its problems must match `expect`.
const SELF_TEST_CASES = [
  { check: 'no-emoji', expect: /seed-emoji\.md:5 emoji U\+2705/ },
  { check: 'no-emoji', expect: /seed-emoji-vs16\.md:3 emoji U\+26A0 U\+FE0F/ },
  {
    check: 'no-ai-attribution',
    expect: /seed-attribution\.md:3 AI attribution 'written by Claude Code'/,
  },
  {
    check: 'no-generated-by-line',
    expect: /seed-generated\.md:5 generation attribution 'Generated by some-doc-tool v3'/,
  },
  {
    check: 'no-assistant-boilerplate',
    expect: /seed-boilerplate\.md:3 assistant boilerplate 'As an AI'/,
  },
  {
    check: 'no-assistant-boilerplate',
    expect: /seed-boilerplate\.md:3 assistant boilerplate 'I cannot'/,
  },
  // The allowance is path-scoped: the same quotation elsewhere still fails.
  ...(ALLOWED_ENTRY
    ? [
        {
          check: 'no-assistant-boilerplate',
          expect: /legacy[\\/]other-quote\.md:\d+ assistant boilerplate/,
        },
      ]
    : []),
  // The allowance naming STALE_FILE suppresses nothing here, so it is reported.
  ...(STALE_ENTRY
    ? [
        {
          check: 'style-allowances-live',
          expect: new RegExp(`allowance \\d+ \\(${escapeRe(STALE_FILE)},`),
        },
      ]
    : []),
];

// Negative cases: shapes no rule may flag — the proof the rules are narrow.
const NEGATIVE_SELF_TEST_CASES = [
  { check: 'no-emoji', forbid: /clean\.md/ },
  { check: 'no-ai-attribution', forbid: /clean\.md/ },
  { check: 'no-generated-by-line', forbid: /clean\.md/ },
  { check: 'no-assistant-boilerplate', forbid: /clean\.md/ },
  // The walk stops at the edge of this checkout.
  { check: 'no-assistant-boilerplate', forbid: /nested-checkout/ },
  { check: 'no-assistant-boilerplate', forbid: /(^|[/\\])\.claude[/\\]/ },
  // The allowance does its job on the file it names…
  ...(ALLOWED_ENTRY
    ? [
        { check: 'no-assistant-boilerplate', forbid: new RegExp(escapeRe(ALLOWED_FILE)) },
        // …and having done so, it is not reported as stale.
        {
          check: 'style-allowances-live',
          forbid: new RegExp(`allowance \\d+ \\(${escapeRe(ALLOWED_FILE)},`),
        },
      ]
    : []),
];

function runSelfTest() {
  const fixtureRoot = buildSelfTestFixture();
  const failures = [];
  try {
    const files = walkFiles(fixtureRoot, { exts: MD_EXTS });
    const byName = new Map(runStyleChecks(files, fixtureRoot).checks.map((c) => [c.name, c]));
    for (const { check, expect } of SELF_TEST_CASES) {
      const result = byName.get(check);
      if (!result) {
        failures.push(`${check}: unknown check`);
        continue;
      }
      if (result.problems.length === 0) {
        failures.push(`${check}: did NOT fail on the seeded violation — the check is vacuous`);
        continue;
      }
      if (!result.problems.some((p) => expect.test(p))) {
        failures.push(
          `${check}: failed, but not on the seeded violation (${expect}); got: ${result.problems.join(' | ')}`,
        );
      }
    }
    for (const { check, forbid } of NEGATIVE_SELF_TEST_CASES) {
      const result = byName.get(check);
      if (!result) {
        failures.push(`${check}: unknown check (negative case)`);
        continue;
      }
      const wrong = result.problems.find((p) => forbid.test(p));
      if (wrong) {
        failures.push(
          `${check}: flagged a legitimate shape (${forbid}) — the rule is too broad: ${wrong}`,
        );
      }
    }
  } finally {
    fs.rmSync(fixtureRoot, { recursive: true, force: true });
  }
  return { cases: SELF_TEST_CASES.length + NEGATIVE_SELF_TEST_CASES.length, failures };
}

function main() {
  if (process.argv.slice(2).includes('--self-test')) {
    const { cases, failures } = runSelfTest();
    if (failures.length > 0) {
      console.error(`SELF-TEST FAIL (${failures.length}/${cases} cases):`);
      for (const f of failures) console.error(`  - ${f}`);
      process.exit(1);
    }
    console.log(
      `SELF-TEST PASS — all ${cases} cases hold (style rules fail on seeded violations, legitimate shapes stay unflagged)`,
    );
    process.exit(0);
  }

  let registry;
  try {
    registry = readJson(path.join(REPO_ROOT, REGISTRY_REL));
  } catch (err) {
    console.error(`FAIL ${REGISTRY_REL} unreadable: ${err.message}`);
    process.exit(1);
  }

  const files = mdFiles();
  const checks = [
    { name: 'internal-links', problems: checkLinks(files) },
    { name: 'readme-current-phase', problems: checkReadmePhase(registry) },
    { name: 'phase-report-exists', problems: checkPhaseReport(registry) },
    { name: 'phase-status-consistency', problems: checkPhaseStatusConsistency(files) },
    { name: 'derived-facts', problems: checkDerivedFacts() },
    { name: 'adr-references', problems: checkAdrReferences(files) },
    { name: 'module-docs', problems: checkModuleDocs() },
    { name: 'mermaid-sanity', problems: checkMermaid(files) },
    { name: 'phase-template-sections', problems: checkPhaseTemplate() },
    ...runStyleChecks(files, REPO_ROOT).checks,
  ];

  console.log(`Documentation checks — ${files.length} markdown files scanned`);
  console.log('');
  let failed = 0;
  for (const { name, problems } of checks) {
    const status = problems.length === 0 ? 'PASS' : 'FAIL';
    if (problems.length > 0) failed += 1;
    console.log(`${status.padEnd(7)} ${name}${problems.length > 0 ? ` (${problems.length})` : ''}`);
    for (const p of problems) console.log(`          ${p}`);
  }

  // Self-test at the end of every run: prove the style passes above are not
  // vacuous on the same invocation that reports them.
  const { cases, failures: selfTestFailures } = runSelfTest();
  console.log('');
  if (selfTestFailures.length > 0) {
    console.error(`SELF-TEST FAIL (${selfTestFailures.length}/${cases} cases):`);
    for (const f of selfTestFailures) console.error(`  - ${f}`);
  } else {
    console.log(
      `SELF-TEST PASS — all ${cases} cases hold (style rules fail on seeded violations, legitimate shapes stay unflagged)`,
    );
  }

  const ok = failed === 0 && selfTestFailures.length === 0;
  console.log('');
  console.log(
    `Summary: ${checks.length - failed}/${checks.length} checks passed; self-test: ${
      selfTestFailures.length === 0 ? 'ok' : 'FAILED'
    }`,
  );

  const outDir = ensureOutDir(REPO_ROOT);
  const report = {
    generatedAt: new Date().toISOString(),
    ok,
    filesScanned: files.length,
    checks: checks.map(({ name, problems }) => ({
      name,
      status: problems.length === 0 ? 'PASS' : 'FAIL',
      problems,
    })),
    selfTest: { cases, failures: selfTestFailures },
  };
  fs.writeFileSync(path.join(outDir, 'docs-report.json'), `${JSON.stringify(report, null, 2)}\n`);
  console.log('Report: scripts/checks/.out/docs-report.json');

  process.exit(ok ? 0 : 1);
}

main();
